### ISSUE TITLE
RNAtools2 dependency

### ISSUE THREAD

**Issue by peaceben** [Weeks-UNC/arcPlot#1]
Dear Anthony,

sorry for bothering with a question, which might have an obvious solution. But an y hints on how to fulfill the RNAtools2 requirement for arcplot? Anything else works like a charme. 

Thanks in advance,
Ben

**Comment by anthonymustoe** [comment]
Sorry Ben for not seeing this until now! RNAtools2 is distributed in the RNATools package (available at the Weeks-UNC github page)
